WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
VIRTURE_WIDTH = 432
VIRTURE_HEIGHT = 243

PADDLE_HEIGHT = 16
PADDLE_BASE_WIDTH = 32

BALL_SIZE = PADDLE_BASE_WIDTH / 4

BLOCK_WIDTH = PADDLE_BASE_WIDTH
BLOCK_HEIGHT = PADDLE_HEIGHT
